name: myrideup
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  email_validator: "^2.1.16"
  intl_phone_field: ^3.2.0
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  firebase_database: ^10.2.7
  firebase_storage: ^11.2.8
  firebase_messaging: ^14.6.9
  fluttertoast: ^8.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

assets:
  - assets/images/bluescene.jpg
  - assets/images/boat.jpg
