name: myrideup
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  email_validator: "^2.1.16"
  intl_phone_field: ^3.2.0
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  firebase_database: ^10.2.7
  firebase_storage: ^11.2.8
  firebase_messaging: ^14.6.9
  fluttertoast: ^8.2.2
  google_maps_flutter: ^2.5.0
  url_launcher: ^6.2.1
  geolocator: ^10.1.0
  geocoder2: ^1.4.0
  flutter_geofire: ^2.0.3
  flutter_polyline_points: ^1.0.0
  location: ^5.0.0
  smooth_star_rating_nsafe: ^1.0.0+1
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
