// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM3pCJMLiwO82HqWsStolDm0BCTOZBd6I',
    appId: '1:785680923965:web:d724d1ce60b0a862885954',
    messagingSenderId: '785680923965',
    projectId: 'myrideup',
    authDomain: 'myrideup.firebaseapp.com',
    databaseURL: 'https://myrideup-default-rtdb.firebaseio.com',
    storageBucket: 'myrideup.appspot.com',
    measurementId: 'G-931BR24WYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPbbtS64jmhkKNt2PdaHZ6ESwCklIHqXg',
    appId: '1:785680923965:android:ecf174d0451db2b9885954',
    messagingSenderId: '785680923965',
    projectId: 'myrideup',
    databaseURL: 'https://myrideup-default-rtdb.firebaseio.com',
    storageBucket: 'myrideup.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh30TDg2E15kFpGroqXNiQJyTQEI3BhVo',
    appId: '1:785680923965:ios:bb8406c6e5ab5e8f885954',
    messagingSenderId: '785680923965',
    projectId: 'myrideup',
    databaseURL: 'https://myrideup-default-rtdb.firebaseio.com',
    storageBucket: 'myrideup.appspot.com',
    iosBundleId: 'com.example.myrideup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh30TDg2E15kFpGroqXNiQJyTQEI3BhVo',
    appId: '1:785680923965:ios:e54d4062174b4eca885954',
    messagingSenderId: '785680923965',
    projectId: 'myrideup',
    databaseURL: 'https://myrideup-default-rtdb.firebaseio.com',
    storageBucket: 'myrideup.appspot.com',
    iosBundleId: 'com.example.myrideup.RunnerTests',
  );
}
